export const UNIT_OF_WORK = Symbol('UNIT_OF_WORK');
export const CONVERSION_REPOSITORY = Symbol('CONVERSION_REPOSITORY');
export const OUTBOX_REPOSITORY = Symbol('OUTBOX_REPOSITORY');
export const PROCESSED_MESSAGE_REPOSITORY = Symbol('PROCESSED_MESSAGE_REPOSITORY');
export const EXCHANGE_EXECUTION = Symbol('EXCHANGE_EXECUTION');
export const IDEMPOTENCY_REPOSITORY = Symbol('IDEMPOTENCY_REPOSITORY');
